In [1]:
%pip install duckdb pandas matplotlib seaborn plotly numpy openpyxl

Collecting duckdb
  Using cached duckdb-1.4.4-cp312-cp312-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl.metadata (4.3 kB)
Requirement already satisfied: pandas in /home/mariia/Documents/Documents/Masha/comp3122/PyData2025/PyData2025/Lab_Week10_RegressionMPG/.venv/lib/python3.12/site-packages (2.3.3)
Requirement already satisfied: matplotlib in /home/mariia/Documents/Documents/Masha/comp3122/PyData2025/PyData2025/Lab_Week10_RegressionMPG/.venv/lib/python3.12/site-packages (3.10.7)
Requirement already satisfied: seaborn in /home/mariia/Documents/Documents/Masha/comp3122/PyData2025/PyData2025/Lab_Week10_RegressionMPG/.venv/lib/python3.12/site-packages (0.13.2)
Collecting plotly
  Using cached plotly-6.5.2-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: numpy in /home/mariia/Documents/Documents/Masha/comp3122/PyData2025/PyData2025/Lab_Week10_RegressionMPG/.venv/lib/python3.12/site-packages (2.3.4)
Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/mariia/Documents/Documents/Masha/comp3122/PyData2025/PyData2025/Lab_Week10_RegressionMPG/.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/mariia/Documents/Documents/Masha/comp3122/PyData2025/PyData2025/Lab_Week10_RegressionMPG/.venv/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/mariia/Documents/Documents/Masha/comp3122/PyData2025/PyData2025/Lab_Week10_RegressionMPG/.venv/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in /home/mariia/Documents/Documents/Masha/comp3122/PyData2025/PyData2025/Lab_Week10_RegressionMPG/.venv/lib/python3.12/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /home/mariia/Documents/Documents/Masha/comp3122/PyData2025/PyData2025/Lab_Week10_RegressionMPG/.venv/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/mariia/Documents/Documents/Masha/comp3122/PyData2025/PyData2025/Lab_Week10_RegressionMPG/.venv/lib/python3.12/site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/mariia/Documents/Documents/Masha/comp3122/PyData2025/PyData2025/Lab_Week10_RegressionMPG/.venv/lib/python3.12/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /home/mariia/Documents/Documents/Masha/comp3122/PyData2025/PyData2025/Lab_Week10_RegressionMPG/.venv/lib/python3.12/site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in /home/mariia/Documents/Documents/Masha/comp3122/PyData2025/PyData2025/Lab_Week10_RegressionMPG/.venv/lib/python3.12/site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=3 in /home/mariia/Documents/Documents/Masha/comp3122/PyData2025/PyData2025/Lab_Week10_RegressionMPG/.venv/lib/python3.12/site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: narwhals>=1.15.1 in /home/mariia/Documents/Documents/Masha/comp3122/PyData2025/PyData2025/Lab_Week10_RegressionMPG/.venv/lib/python3.12/site-packages (from plotly) (2.15.0)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: six>=1.5 in /home/mariia/Documents/Documents/Masha/comp3122/PyData2025/PyData2025/Lab_Week10_RegressionMPG/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached duckdb-1.4.4-cp312-cp312-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl (20.4 MB)
Using cached plotly-6.5.2-py3-none-any.whl (9.9 MB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: plotly, et-xmlfile, duckdb, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [openpyxl]3/4 [openpyxl]
Successfully installed duckdb-1.4.4 et-xmlfile-2.0.0 openpyxl-3.1.5 plotly-6.5.2

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [7]:
import pandas as pd
import duckdb



con = duckdb.connect()
df_volunteers= pd.read_csv("../data/all_volunteers.csv")

df_hours = pd.read_csv("../data/volunteer_hour_log.csv")

con.register("volunteers", df_volunteers)
con.register("hours", df_hours)

con.execute("""
CREATE VIEW raw_volunteers AS
SELECT *
FROM read_csv_auto('../data/all_volunteers.csv', strict_mode = false);
""")

con.execute("""
CREATE VIEW raw_hours AS
SELECT *
FROM read_csv_auto('../data/volunteer_hour_log.csv', strict_mode = false);
""")

In [8]:
query = """
SELECT *
FROM raw_volunteers
LIMIT 20
"""
df_volunteers_sample = con.execute(query).df()
df_volunteers_sample

,Name,Item ID,Participant ID,Creation log,What type of placement are you interested in?,Which province do you reside in?,Canadian citizen or PR,Official Language Preference,First Time Volunteer,Have you joined a Canada Service Corp Program in the past?,...,Referee Summary,Sum Up Task 1,Sum Up Task 2,Volunteer Milestones,Text,Share account info,Status,link to Camp staff/volunteer evaluation,Evaluations,Last hour log
0,Mariam Ali,10031967966,N0559,"U+ HR Account Sep 11, 2025 1:30 PM",100% In-Person,Ontario,<NA>,English,False,False,...,None,None,None,None,NaT,None,None,None,None,None
1,Manusha Srikanthan,10032126283,N0561,"blank Sep 11, 2025 1:45 PM",100% In-Person,Ontario,<NA>,English,False,False,...,None,None,None,None,NaT,None,None,None,None,None
2,Harvi Shah,10033950641,N0563,"blank Sep 11, 2025 4:36 PM","Some virtual, some in-person",British Columbia,<NA>,English,False,False,...,None,None,None,None,NaT,None,None,None,None,None
3,Dorsey Bangarh,10034418759,N0565,"blank Sep 11, 2025 5:37 PM","Some virtual, some in-person",British Columbia,<NA>,English,True,<NA>,...,None,None,None,None,NaT,None,None,None,None,None
4,Pushti Ladani,10034960446,N0567,"blank Sep 11, 2025 7:26 PM",100% Virtual,Ontario,<NA>,English,True,<NA>,...,None,None,None,None,NaT,None,None,None,None,None
5,Purti Ladani,10034969760,N0568,"blank Sep 11, 2025 7:29 PM",100% Virtual,Ontario,<NA>,English,True,<NA>,...,None,None,None,None,NaT,None,None,None,None,None
6,Harjot Singh,10035306947,N0570,"blank Sep 11, 2025 8:52 PM",100% Virtual,Ontario,<NA>,English,True,<NA>,...,None,None,None,None,NaT,Email sent,None,None,None,None
7,Rincy Nahomie,10035241947,N0569,"blank Sep 11, 2025 8:31 PM",100% In-Person,Ontario,<NA>,French,False,False,...,None,None,None,None,NaT,None,None,None,None,None
8,JeeHu Choi,10035315192,N0571,"blank Sep 11, 2025 8:55 PM","Some virtual, some in-person",Ontario,<NA>,English,True,<NA>,...,Leslie Usin-Rojas,None,None,None,NaT,Shared in call,None,None,None,None
9,Taranveer Arora,10035436889,N0572,"blank Sep 11, 2025 9:32 PM",100% Virtual,Ontario,<NA>,English,True,<NA>,...,None,Virtual Volunteer Data Analysis Assistant,None,None,NaT,Shared in call,None,None,None,None
10,Luong Hai Ha Bui,10035520719,N0573,"blank Sep 11, 2025 10:03 PM","Some virtual, some in-person",Ontario,<NA>,English,False,False,...,None,None,None,None,NaT,Shared in call,None,None,None,None
11,Pranav Kumar,10035540047,N0574,"blank Sep 11, 2025 10:12 PM",100% Virtual,Ontario,<NA>,English,False,False,...,None,None,None,None,NaT,Shared in call,None,None,None,None
12,Amy Badley,10038042234,N0576,"blank Sep 12, 2025 9:22 AM",Flexible - I can do any format,Ontario,<NA>,English,True,<NA>,...,None,None,None,None,NaT,None,None,None,None,None
13,Laoel Beqiri,10039175828,N0578,"blank Sep 12, 2025 11:03 AM",Flexible - I can do any format,Ontario,<NA>,English,True,<NA>,...,Matt Parry,None,None,None,NaT,None,None,None,None,None
14,Alexander Artunduaga,10038193035,N0577,"blank Sep 12, 2025 9:36 AM",Flexible - I can do any format,Ontario,<NA>,English,True,<NA>,...,Emily Zupnik,None,None,None,NaT,Email sent,None,None,None,None
15,Asher Tsang,10039461647,N0579,"blank Sep 12, 2025 11:33 AM",100% Virtual,Ontario,<NA>,English,False,False,...,None,None,None,None,NaT,None,None,None,None,None
16,Mei Lin Sheaves,10040288225,N0580,"blank Sep 12, 2025 1:00 PM","Some virtual, some in-person",British Columbia,<NA>,English,False,False,...,NA,None,None,None,NaT,None,None,None,None,None
17,Akshata Naik,10040309708,N0581,"blank Sep 12, 2025 1:02 PM",100% Virtual,Alberta,<NA>,English,True,<NA>,...,None,None,None,None,NaT,None,None,None,None,None
18,Simranjit Kaur,10041033488,N0582,"blank Sep 12, 2025 2:22 PM",Flexible - I can do any format,Ontario,<NA>,French,True,<NA>,...,None,None,None,None,NaT,None,None,None,None,None
19,Jason Ngo,10043050443,N0585,"blank Sep 12, 2025 8:13 PM",100% Virtual,Ontario,<NA>,English,False,False,...,None,None,None,None,NaT,None,None,None,None,None

In [9]:
query = """
SELECT *
FROM raw_hours
LIMIT 20
"""
df_hours_sample = con.execute(query).df()
df_hours_sample

,First Name,Your Last Name,Creation Log,Email,Volunteering Date,Total Volunteering Hours Completed Today,Please describe the volunteering activities completed today,log type
0,Adyan,Haque,"Kevin Jul 26, 2025 3:44 PM",adyan.haque@yorkeducation.ca,2025-07-26,1.5,Completed training resources training,Training
1,Adyan,Haque,"Kevin Jul 26, 2025 11:22 PM",adyan.haque@yorkeducation.ca,2025-07-26,6.0,completed IMPACT training,Training
2,Sophia,Pan,"Kevin Oct 19, 2025 2:31 PM",sophia875665@gmail.com,2025-10-19,4.0,I participated in the halloween howl event fro...,Service
3,Raff,Shang,"Kevin Oct 19, 2025 12:17 PM",raffshang.0506@gmail.com,2025-10-19,6.0,I helped setting up the activities and keeping...,Service
4,Allen,Lin,"Kevin Oct 19, 2025 12:44 PM",sunflowerlin2010@gmail.com,2025-10-19,2.0,I created a comic that could help encourage ot...,Service
5,Allen,Lin,"Kevin Oct 19, 2025 12:46 PM",sunflowerlin2010@gmail.com,2025-09-03,2.5,I created a video to help promote volunteering...,Service
6,Allen,Lin,"Kevin Oct 19, 2025 12:48 PM",sunflowerlin2010@gmail.com,2025-08-22,2.5,I did a analysis task on what I thought YRES c...,Service
7,Allen,Lin,"Kevin Oct 19, 2025 12:49 PM",sunflowerlin2010@gmail.com,2025-08-27,0.5,I practiced using Canva and made a video using it,Service
8,Araoluwa,Odufalu,"Kevin Oct 19, 2025 1:38 PM",araoluwa.odufalu2@gmail.com,2025-10-19,4.0,"I helped set up stalls, brought in equipment, ...",Service
9,Janice,Zheng,"Kevin Oct 19, 2025 2:42 PM",janicezheng163@gmail.com,2025-10-19,4.0,I helped set up and guide the parade at the Ha...,Service
10,Carmen,Hua,"Kevin Oct 20, 2025 8:09 AM",carmen.hua@yorkeducation.ca,2025-10-19,4.0,I helped out on setting up the stand and other...,Service
11,Jahid,Ullah,"Kevin Oct 21, 2025 7:15 PM",jahid1998ullah@gmail.com,2025-10-21,3.0,"I participated in the YRES Job Fair, where I a...",Service
12,Adrian,So,"Kevin Oct 25, 2025 4:41 PM",adrian.so@yorkeducation.ca,2025-10-25,3.5,I volunteered for the YRES X Ignite Fair at Th...,Service
13,Sinaz,Heidari,"Kevin Aug 4, 2025 1:30 PM",sinazheidari1380@gmail.com,2025-08-01,16.0,"Team building, outdoor, gym, STEAM",Service
14,Sinaz,Heidari,"Kevin Jul 29, 2025 4:46 PM",sinazheidari1380@gmail.com,2025-07-29,8.0,"Outdoors, team building, gym, STEAM",Service
15,Sinaz,Heidari,"Kevin Jul 27, 2025 1:02 PM",sinazheidari1380@gmail.com,2025-07-25,8.0,"outdoor activities, gym, STEAM, team building",Service
16,Sinaz,Heidari,"Kevin Jul 24, 2025 10:15 PM",sinazheidari1380@gmail.com,2025-07-24,8.0,"Outdoors, gym, team building, experiment",Service
17,Sinaz,Heidari,"Kevin Jul 31, 2025 4:33 PM",sinazheidari1380@gmail.com,2025-07-31,8.0,"Team building, dance practice, science, teamwork",Service
18,Sinaz,Heidari,"Kevin Jul 28, 2025 4:20 PM",sinazheidari1380@gmail.com,2025-07-28,8.0,"Outdoors, team building, gym, STEAM",Service
19,Sinaz,Heidari,"Kevin Jul 8, 2025 8:02 PM",sinazheidari1380@gmail.com,2025-07-08,8.0,We did a what do u wanna say to yourself in 10...,Service

In [ ]:
con.execute(r"""
CREATE OR REPLACE VIEW clean_volunteers AS
WITH base AS (
  SELECT
    TRIM(Name) AS full_name,

    -- 1) extract "Sep 26, 2025 3:07 AM" from the messy text
    regexp_extract(
      "Creation Log",
      '([A-Z][a-z]{2}\s+\d{1,2},\s+\d{4}\s+\d{1,2}:\d{2}\s+[AP]M)',
      1
    ) AS date_joined_vps,

    LOWER(TRIM("Email Address")) AS email,
    

  FROM raw_volunteers
)
SELECT
  full_name,

  -- 2) parse into TIMESTAMP (safe)
  TRY_STRPTIME(date_joined_vps, '%b %d, %Y %I:%M %p') AS date_joined_vps,

  email,
FROM base
WHERE full_name IS NOT NULL
""")

df_volunteers_clean = con.execute("""
SELECT *
FROM clean_volunteers
LIMIT 20
""").df()

df_volunteers_clean

,full_name,date_joined_vps,email
0,Mariam Ali,2025-09-11 13:30:00,mariam.ali@yorkeducation.ca
1,Manusha Srikanthan,2025-09-11 13:45:00,manushasrikanthan@gmail.com
2,Harvi Shah,2025-09-11 16:36:00,harvishah2602@gmail.com
3,Dorsey Bangarh,2025-09-11 17:37:00,dorseybangarh2004@gmail.com
4,Pushti Ladani,2025-09-11 19:26:00,pushti-kantilal.ladani@mohawkcollege.ca
5,Purti Ladani,2025-09-11 19:29:00,purti1002@gmail.com
6,Harjot Singh,2025-09-11 20:52:00,singhharjot1312@gmail.com
7,Rincy Nahomie,2025-09-11 20:31:00,rincynahomie85@gmail.com
8,JeeHu Choi,2025-09-11 20:55:00,jiwhotwin@gmail.com
9,Taranveer Arora,2025-09-11 21:32:00,taransarora@gmail.com
10,Luong Hai Ha Bui,2025-09-11 22:03:00,habui151103@gmail.com
11,Pranav Kumar,2025-09-11 22:12:00,pranav.in.kumar@gmail.com
12,Amy Badley,2025-09-12 09:22:00,icetea565@gmail.com
13,Laoel Beqiri,2025-09-12 11:03:00,laodebeqirize@gmail.com
14,Alexander Artunduaga,2025-09-12 09:36:00,alexander.artunduaga.1209@gmail.com
15,Asher Tsang,2025-09-12 11:33:00,itsatsang@gmail.com
16,Mei Lin Sheaves,2025-09-12 13:00:00,meilinsheaves@gmail.com
17,Akshata Naik,2025-09-12 13:02:00,05akshatanaik@gmail.com
18,Simranjit Kaur,2025-09-12 14:22:00,simrann1nov@gmail.com
19,Jason Ngo,2025-09-12 20:13:00,ngo_jason@outlook.com

In [17]:
con.execute(r"""
CREATE OR REPLACE VIEW clean_hours AS
WITH base AS (
    SELECT
        TRIM("First Name") AS first_name,
        TRIM("Your Last Name") AS last_name,
        TRIM("First Name") || ' ' || TRIM("Your Last Name") AS full_name,

        -- extract "Sep 26, 2025 3:07 AM"
        regexp_extract(
            "Creation Log",
            '([A-Z][a-z]{2}\s+\d{1,2},\s+\d{4}\s+\d{1,2}:\d{2}\s+[AP]M)',
            1
        ) AS date_joined_vps_str,

        LOWER(TRIM("Email")) AS email,

        -- already a DATE in most CSVs
        TRY_CAST("Volunteering Date" AS DATE) AS volunteering_date,

        "Total Volunteering Hours Completed Today" AS total_hours,
        "log type" AS log_type
    FROM raw_hours
)
SELECT
    first_name,
    last_name,
    full_name,
    TRY_STRPTIME(date_joined_vps_str, '%b %d, %Y %I:%M %p') AS date_joined_vps,
    email,
    volunteering_date,
    total_hours,
    log_type
FROM base
WHERE full_name IS NOT NULL;
""")


df_hours_clean = con.execute("""
SELECT *
FROM clean_hours
LIMIT 20
""").df()
df_hours_clean

,first_name,last_name,full_name,date_joined_vps,email,volunteering_date,total_hours,log_type
0,Adyan,Haque,Adyan Haque,2025-07-26 15:44:00,adyan.haque@yorkeducation.ca,2025-07-26,1.5,Training
1,Adyan,Haque,Adyan Haque,2025-07-26 23:22:00,adyan.haque@yorkeducation.ca,2025-07-26,6.0,Training
2,Sophia,Pan,Sophia Pan,2025-10-19 14:31:00,sophia875665@gmail.com,2025-10-19,4.0,Service
3,Raff,Shang,Raff Shang,2025-10-19 12:17:00,raffshang.0506@gmail.com,2025-10-19,6.0,Service
4,Allen,Lin,Allen Lin,2025-10-19 12:44:00,sunflowerlin2010@gmail.com,2025-10-19,2.0,Service
5,Allen,Lin,Allen Lin,2025-10-19 12:46:00,sunflowerlin2010@gmail.com,2025-09-03,2.5,Service
6,Allen,Lin,Allen Lin,2025-10-19 12:48:00,sunflowerlin2010@gmail.com,2025-08-22,2.5,Service
7,Allen,Lin,Allen Lin,2025-10-19 12:49:00,sunflowerlin2010@gmail.com,2025-08-27,0.5,Service
8,Araoluwa,Odufalu,Araoluwa Odufalu,2025-10-19 13:38:00,araoluwa.odufalu2@gmail.com,2025-10-19,4.0,Service
9,Janice,Zheng,Janice Zheng,2025-10-19 14:42:00,janicezheng163@gmail.com,2025-10-19,4.0,Service
10,Carmen,Hua,Carmen Hua,2025-10-20 08:09:00,carmen.hua@yorkeducation.ca,2025-10-19,4.0,Service
11,Jahid,Ullah,Jahid Ullah,2025-10-21 19:15:00,jahid1998ullah@gmail.com,2025-10-21,3.0,Service
12,Adrian,So,Adrian So,2025-10-25 16:41:00,adrian.so@yorkeducation.ca,2025-10-25,3.5,Service
13,Sinaz,Heidari,Sinaz Heidari,2025-08-04 13:30:00,sinazheidari1380@gmail.com,2025-08-01,16.0,Service
14,Sinaz,Heidari,Sinaz Heidari,2025-07-29 16:46:00,sinazheidari1380@gmail.com,2025-07-29,8.0,Service
15,Sinaz,Heidari,Sinaz Heidari,2025-07-27 13:02:00,sinazheidari1380@gmail.com,2025-07-25,8.0,Service
16,Sinaz,Heidari,Sinaz Heidari,2025-07-24 22:15:00,sinazheidari1380@gmail.com,2025-07-24,8.0,Service
17,Sinaz,Heidari,Sinaz Heidari,2025-07-31 16:33:00,sinazheidari1380@gmail.com,2025-07-31,8.0,Service
18,Sinaz,Heidari,Sinaz Heidari,2025-07-28 16:20:00,sinazheidari1380@gmail.com,2025-07-28,8.0,Service
19,Sinaz,Heidari,Sinaz Heidari,2025-07-08 20:02:00,sinazheidari1380@gmail.com,2025-07-08,8.0,Service

## Question 1. In Jan 2026, who participated in volunteering and for how many hours

In [31]:
query = """
SELECT
  v.full_name,
  v.email,
  v.date_joined_vps,

  -- January 2026 only
  SUM(CASE
        WHEN h.log_type = 'Training'
         AND h.volunteering_date >= DATE '2026-01-01'
         AND h.volunteering_date <  DATE '2026-02-01'
        THEN h.total_hours ELSE 0
      END) AS training_hours_jan_2026,

  SUM(CASE
        WHEN h.log_type = 'Service'
         AND h.volunteering_date >= DATE '2026-01-01'
         AND h.volunteering_date <  DATE '2026-02-01'
        THEN h.total_hours ELSE 0
      END) AS service_hours_jan_2026,

  -- all time totals
  SUM(CASE WHEN h.log_type = 'Training' THEN h.total_hours ELSE 0 END)
    AS training_hours_total,

  SUM(CASE WHEN h.log_type = 'Service' THEN h.total_hours ELSE 0 END)
    AS service_hours_total

FROM clean_volunteers v
LEFT JOIN clean_hours h
  ON v.email = h.email

GROUP BY
  v.email,
  v.full_name,
  v.date_joined_vps

ORDER BY
  service_hours_jan_2026 DESC,
  training_hours_jan_2026 DESC;

"""
df_jan_2026_hours = con.execute(query).df()
df_jan_2026_hours.to_excel("../data/jan_2026_volunteer_hours.xlsx", index=False)

## Question 2. By Dec 31, 2025, how many VSP volunteers have completed hours in each of the following range:
0-40hrs
40-80hrs
80-120hrs
Above 120hrs

In [33]:
query = """
WITH hours_by_volunteer AS (
  SELECT
    email,
    SUM(total_hours) AS total_hours
  FROM clean_hours
  WHERE volunteering_date <= DATE '2025-12-31'
  GROUP BY email
)
SELECT
  CASE
    WHEN total_hours >= 0   AND total_hours < 40  THEN '0–40 hrs'
    WHEN total_hours >= 40  AND total_hours < 80  THEN '40–80 hrs'
    WHEN total_hours >= 80  AND total_hours < 120 THEN '80–120 hrs'
    ELSE 'Above 120 hrs'
  END AS hour_range,

  COUNT(*) AS volunteer_count

FROM hours_by_volunteer
GROUP BY hour_range
ORDER BY
  CASE hour_range
    WHEN '0–40 hrs' THEN 1
    WHEN '40–80 hrs' THEN 2
    WHEN '80–120 hrs' THEN 3
    ELSE 4
  END;
"""
df_hours_range = con.execute(query).df()
df_hours_range.to_excel("../data/volunteer_hours_range_by_dec_31_2025.xlsx", index=False)